# Generated by Django 5.2.8 on 2025-12-02 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_email', models.EmailField(help_text='Email of the person signing', max_length=254)),
                ('signer_name', models.CharField(help_text='Full name of signer', max_length=255)),
                ('original_pdf', models.FileField(help_text='Original uploaded PDF', upload_to='esign/originals/%Y/%m/%d/')),
                ('signed_pdf', models.FileField(blank=True, help_text='Signed PDF with embedded signatures', null=True, upload_to='esign/signed/%Y/%m/%d/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('original_file_size', models.BigIntegerField(default=0, help_text='Original file size in bytes')),
                ('signed_file_size', models.BigIntegerField(default=0, help_text='Signed file size in bytes')),
                ('original_pdf_hash', models.CharField(help_text='SHA-256 hash of original', max_length=64)),
                ('signed_pdf_hash', models.CharField(blank=True, help_text='SHA-256 hash of signed PDF', max_length=64, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('signing', 'Signing in Progress'), ('signed', 'Signed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='created', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Session expiration time')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for async processing', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error message if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who created this session (if via web UI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sign Session',
                'verbose_name_plural': 'Sign Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField(help_text='PDF page number (1-indexed)')),
                ('x', models.FloatField(help_text='X coordinate (points)')),
                ('y', models.FloatField(help_text='Y coordinate (points)')),
                ('width', models.FloatField(help_text='Field width (points)')),
                ('height', models.FloatField(help_text='Field height (points)')),
                ('name', models.CharField(help_text='Field identifier', max_length=100)),
                ('label', models.CharField(blank=True, help_text='Display label', max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Signing order for multi-field')),
                ('is_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_fields', to='esign.signsession')),
            ],
            options={
                'verbose_name': 'Signature Field',
                'verbose_name_plural': 'Signature Fields',
                'ordering': ['session', 'order', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('draw', 'Drawn'), ('upload', 'Uploaded Image'), ('type', 'Typed Name')], max_length=10)),
                ('signature_image', models.FileField(help_text='Signature image (PNG with transparency)', upload_to='esign/signatures/%Y/%m/%d/')),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_reason', models.TextField(blank=True, help_text='Reason for signing')),
                ('signer_location', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('font_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='esign.signaturefield')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='esign.signsession')),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(help_text='Hashed OTP code', max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='esign.signsession')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('session_created', 'Session Created'), ('pdf_uploaded', 'PDF Uploaded'), ('fields_placed', 'Signature Fields Placed'), ('otp_sent', 'OTP Sent'), ('otp_verified', 'OTP Verified'), ('otp_failed', 'OTP Verification Failed'), ('signature_added', 'Signature Added'), ('pdf_signed', 'PDF Signed'), ('session_expired', 'Session Expired'), ('session_cancelled', 'Session Cancelled'), ('download', 'Signed PDF Downloaded')], max_length=30)),
                ('payload', models.JSONField(default=dict, help_text='Event details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='esign.signsession')),
            ],
            options={
                'verbose_name': 'Audit Event',
                'verbose_name_plural': 'Audit Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signsession',
            index=models.Index(fields=['user', '-created_at'], name='esign_signs_user_id_e39883_idx'),
        ),
        migrations.AddIndex(
            model_name='signsession',
            index=models.Index(fields=['signer_email', '-created_at'], name='esign_signs_signer__2c6cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='signsession',
            index=models.Index(fields=['status', '-created_at'], name='esign_signs_status_d35fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='signsession',
            index=models.Index(fields=['expires_at'], name='esign_signs_expires_312ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='signsession',
            index=models.Index(fields=['celery_task_id'], name='esign_signs_celery__f4f76f_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['session', '-created_at'], name='esign_otp_session_778b16_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='esign_otp_expires_29a6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['session', '-created_at'], name='esign_audit_session_e8e444_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', '-created_at'], name='esign_audit_event_t_7ba641_idx'),
        ),
    ]
