# Generated by Django 5.2.9 on 2025-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_fix_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='signsession',
            name='audit_trail_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete audit trail information (session details, signatures, events)'),
        ),
    ]
